name: my_language_app
description: Una aplicación de aprendizaje de idiomas con ChatGPT y HeyGen.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  permission_handler: ^10.4.3
  flutter_spinkit: ^5.2.0
  flutter_animate: ^4.2.0
  avatar_glow: ^2.0.2
  rxdart: ^0.27.7
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  flutter_chat_bubble: ^2.0.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  lottie: ^2.7.0
  just_audio: ^0.9.36
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
    - assets/images/
    - assets/audio/